  
  #Docker for entire job
  
  name: Docker
  on: [ workflow_dispatch]

  jobs: 
    docker_job:
      runs-on: ubuntu-latest
      container: 
        image: node:22-alpine3.19   #ghcr.io/owner/image - github container reg
        # credentials:    ----#if private image
        #   username:
        #   password: 
        env:
          API_URL: some-url.com
        ports:
          - 80
        # volumes:
          # - vol_name:/path/in/container   #---- Names Vol- data persistence-isolated from the host machine but can be shared across container runs if needed.
          # - /path/to/container     #---- Anonymous vol- temporary storage-
          # - /path/in/host:/path/on/container     #---- Bind mounts--host machine path mapped to path in container-Provide direct access to files on the host machine, useful for sharing configuration files, accessing code, and debugging.
        # options: -- cpus 1  #---- any other option post to docker create cmd, except n/w and entry point-  limits the container to use a maximum of 1 CPU.
      
      steps: #steps added will run directly inside container
        - name: Log Node & OS version
          run: |  #multiline string ---node -v to confirm running inside container & ---about OS-alpine3.19 
            node -v
            cat /etc/os-release
          #display the content of a file that lives in etc/os-release  

        - name: Log Env                     #---to confirm inside container access to env var
          run: echo $API_URL                #--- all these steps will run inside of container                

        #Docker for specific step

        - name: conatiner in a step
          uses: docker://node:20-alpine3.19
          # with:
          #   entrypoint: #path of the node install in my local/ubuntu - type node
          #   args:  -p 2+3
        - name: Log node version
          uses: docker://node:20-alpine3.19
          with:
            args: -v

            # node:22-alpine3.19 and docker://node:20-alpine3.19 (run on host machine as sibling to 22-alpine)same n/w and vol mounts-communicate

