
name: Docker
on: [ workflow_dispatch]

jobs: 
  docker_job:
    runs-on: ubuntu-latest
    container: 
      image: node:22-alpine3.19   #ghcr.io/owner/image - github container reg
      # credentials:    ----#if private image
      #   username:
      #   password: 
      env:
        API_URL: some-url.com
      ports:
        - 80
      volumes:
        # - vol_name:/path/in/container   #---- Names Vol
        # - /path/to/container     #---- Anonymous vol
        # - /path/in/host:/path/on/container     #---- Bind mounts--host machine path mapped to path in container
      # options: -- cpus 1  #---- any other option post to docker create except n/w and entry point
    
    steps: #steps added will run directly inside container
      - name: Log Node & OS version
        run: |  #multiline string ---- node -v to confirm running inside container --- about OS
          node -v
          cat /etc/os-release

      - name: Log Env                     #---to confirm inside container access to env var
      - run: echo $API_URL                #--- all these steps will run inside of container                

